### ISSUE TITLE
feat(patch): Support `select` getting partial data

### ISSUE THREAD

**Issue by jeffreystoke** [arhat-dev/rs#5]
Given

```yaml
# filename: some.yaml
foo: some-value
```

And

```yaml
bar@file!:
  value: some.yaml
  select: .foo # jq query to pre-process data selected as patch source
```

Then the result will be `bar: some-value`
